### ISSUE TITLE
ConcurrentModificationException in IndexRequestQueue's executeRequests

### ISSUE THREAD

**Issue by vsaar** [mstein/elasticsearch-grails-plugin#49]
While doing a batch import of some data, I get a `ConcurrentModificationException`, because adding to the `operationBatchList` is not synchronized (as opposed to all other areas where it is modified):

```
java.util.ConcurrentModificationException
    at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:761)
    at java.util.LinkedList$ListItr.next(LinkedList.java:696)
    at org.grails.plugins.elasticsearch.index.IndexRequestQueue.cleanOperationBatchList(IndexRequestQueue.java:243)
    at org.grails.plugins.elasticsearch.index.IndexRequestQueue.executeRequests(IndexRequestQueue.java:138)
    at org.grails.plugins.elasticsearch.index.IndexRequestQueue.executeRequests(IndexRequestQueue.java:123)
    at org.grails.plugins.elasticsearch.ElasticSearchService.doBulkRequest(ElasticSearchService.groovy:281)
    at org.grails.plugins.elasticsearch.ElasticSearchService.index(ElasticSearchService.groovy:151)
    at org.grails.plugins.elasticsearch.ElasticSearchService.index(ElasticSearchService.groovy:160)
    at com.chattee.model.Message$_afterInsert_closure2.doCall(Message.groovy:90)
    at com.chattee.model.Message.afterInsert(Message.groovy:65)
    at org.grails.datastore.mapping.engine.event.AbstractPersistenceEventListener.onApplicationEvent(AbstractPersistenceEventListener.java:46)
...
```

Adding a `synchronized` block around it seems to fix the issue. I'll send a pull request for that.

**Comment by vsaar** [comment]
Pull request has been merged in (#50), so I'm closing this issue.
